name: ultrakey_ui
description: "UltraKey"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  crypto: ^3.0.6
  encrypt: ^5.0.3
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  http: ^1.4.0
  mime: ^2.0.0
  path: ^1.9.1
  pointycastle: ^3.9.1
  url_launcher: ^6.3.1
  win32: ^5.13.0
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/icons/a-filled.png"
    - "assets/icons/b-filled.png"
    - "assets/icons/x-filled.png"
    - "assets/icons/y-filled.png"
    - "assets/icons/dpad.png"
    - "assets/icons/dpad-up.png"
    - "assets/icons/dpad-down.png"
    - "assets/icons/dpad-left.png"
    - "assets/icons/dpad-right.png"
    - "assets/icons/left-bumper.png"
    - "assets/icons/right-bumper.png"
    - "assets/icons/left-joystick-all.png"
    - "assets/icons/left-joystick-down.png"
    - "assets/icons/left-joystick-left.png"
    - "assets/icons/left-joystick-right.png"
    - "assets/icons/left-joystick-up.png"
    - "assets/icons/left-joystick-press.png"
    - "assets/icons/left-joystick.png"
    - "assets/icons/left-stick.png"
    - "assets/icons/left-trigger.png"
    - "assets/icons/menu.png"
    - "assets/icons/view.png"
    - "assets/icons/right-joystick-all.png"
    - "assets/icons/right-joystick-down.png"
    - "assets/icons/right-joystick-left.png"
    - "assets/icons/right-joystick-right.png"
    - "assets/icons/right-joystick-up.png"
    - "assets/icons/right-joystick-press.png"
    - "assets/icons/right-joystick.png"
    - "assets/icons/right-stick.png"
    - "assets/icons/right-trigger.png"
    - "assets/signin.png"